"""OpenAI Codex CLI backend for Aide.

Handles command construction, JSONL event parsing, and context generation
for the ``codex`` CLI tool (``npx codex exec``).

Codex JSONL event types:
    thread.started   -> session (thread_id)
    turn.started     -> ignore
    item.started     -> tool (command_execution in_progress)
    item.completed   -> result (agent_message) / tool (command_execution done)
    turn.completed   -> ignore (usage stats)
"""

import logging
import os
from pathlib import Path
from typing import Any, Dict, List, Optional

from config import generate_auto_context

log = logging.getLogger(__name__)

# ── Types ────────────────────────────────────────────────────────────────

Event = Dict[str, object]
ToolInfo = Dict[str, object]
ParsedEvent = Dict[str, Any]

# ── Command construction ─────────────────────────────────────────────────


def build_cmd(
    prompt: str,
    session_id: Optional[str] = None,
    working_dir: Optional[Path] = None,
    backend_options: Optional[Dict[str, Any]] = None,
) -> list[str]:
    """Build the ``codex exec`` command list."""
    base = ["npx", "codex"]
    options = backend_options or {}

    # -C/--cd is accepted at top-level/exec level, not on exec resume.
    # Place it before subcommands so resume parsing does not fail.
    if working_dir:
        base.extend(["-C", str(working_dir)])

    if session_id:
        # Resume existing session
        cmd = base + ["exec", "resume", session_id, "--json"]
    else:
        cmd = base + ["exec", "--json"]

    skip = os.environ.get("AIDE_CODEX_SKIP_PERMISSIONS", "1").strip().lower()
    if skip in ("1", "true", "yes", "on"):
        cmd.append("--dangerously-bypass-approvals-and-sandbox")
    else:
        cmd.append("--full-auto")

    # Optional profile override (maps to ~/.codex/config.toml [profiles.<name>])
    profile = str(
        options.get("codex_profile")
        or options.get("profile")
        or os.environ.get("AIDE_CODEX_PROFILE", "")
    ).strip()
    if profile:
        cmd.extend(["--profile", profile])

    # Model override
    model = str(
        options.get("codex_model")
        or options.get("model")
        or os.environ.get("AIDE_CODEX_MODEL", "")
    ).strip()
    if model:
        cmd.extend(["-m", model])

    # Optional reasoning effort override for reasoning-capable models
    effort = str(
        options.get("codex_reasoning_effort")
        or options.get("reasoning_effort")
        or os.environ.get("AIDE_CODEX_REASONING_EFFORT", "")
    ).strip().lower()
    effort_aliases = {
        "extra high": "xhigh",
        "extra-high": "xhigh",
        "extra_high": "xhigh",
        "extrahigh": "xhigh",
        "ultra high": "xhigh",
        "ultra-high": "xhigh",
        "ultra_high": "xhigh",
        "ultrahigh": "xhigh",
    }
    effort = effort_aliases.get(effort, effort)
    if effort:
        allowed_efforts = {"minimal", "low", "medium", "high", "xhigh"}
        if effort in allowed_efforts:
            cmd.extend(["-c", f'model_reasoning_effort="{effort}"'])
        else:
            log.warning(
                "Ignoring invalid AIDE_CODEX_REASONING_EFFORT=%r (allowed: %s)",
                effort,
                ", ".join(sorted(allowed_efforts)),
            )

    cmd.append(prompt)
    return cmd


# ── Context generation ───────────────────────────────────────────────────


def gen_context(workspace: Path) -> None:
    """Generate context files for Codex (AGENTS.md + Claude auto files).

    Generates both AGENTS.md (for Codex) and the standard .claude/rules/auto/*
    files (so switching back to Claude works without extra steps).
    """
    # Standard auto files (tasks, cron, skills, projects, CLAUDE.md)
    generate_auto_context(workspace)

    # Build AGENTS.md by combining all rules into one flat file
    _generate_agents_md(workspace)


def _generate_agents_md(workspace: Path) -> None:
    """Combine .claude/rules/*.md + auto/*.md into a single AGENTS.md."""
    sections: List[str] = [
        "<!-- Auto-generated by Aide for Codex CLI. Do not edit. -->\n",
    ]

    rules_dir = workspace / ".claude" / "rules"
    auto_dir = rules_dir / "auto"

    # Read main rule files in order
    for name in ("soul.md", "user.md", "channel.md"):
        path = rules_dir / name
        if path.exists():
            try:
                content = path.read_text(encoding="utf-8").strip()
                if content:
                    sections.append(content)
            except Exception as e:
                log.warning("Failed to read %s: %s", path, e)

    # Read tools.md (symlinked from engine)
    tools_md = rules_dir / "tools.md"
    if tools_md.exists():
        try:
            content = tools_md.read_text(encoding="utf-8").strip()
            if content:
                sections.append(content)
        except Exception:
            pass

    # Read auto-generated files
    if auto_dir.is_dir():
        for name in ("skills.md", "tasks.md", "cron.md", "projects.md"):
            path = auto_dir / name
            if path.exists():
                try:
                    content = path.read_text(encoding="utf-8").strip()
                    if content:
                        sections.append(content)
                except Exception:
                    pass

    # Write AGENTS.md
    agents_md = workspace / "AGENTS.md"
    agents_md.write_text("\n\n---\n\n".join(sections) + "\n", encoding="utf-8")


# ── Event parsing ────────────────────────────────────────────────────────


def parse_event(evt: Event) -> ParsedEvent:
    """Normalize a Codex JSONL event into a standard format.

    Returns ``ParsedEvent`` with keys:
        type: "text" | "tool" | "session" | "result" | "ignore"
        text: extracted text or None
        session_id: thread identifier or None
        tools: list of {name, input} dicts
    """
    parsed: ParsedEvent = {
        "type": "ignore",
        "text": None,
        "session_id": None,
        "tools": [],
    }

    etype = evt.get("type", "")

    # thread.started -> session with thread_id
    if etype == "thread.started":
        tid = evt.get("thread_id")
        if isinstance(tid, str):
            parsed["type"] = "session"
            parsed["session_id"] = tid
        return parsed

    # turn.started / turn.completed -> ignore (turn.completed has usage stats)
    if etype in ("turn.started", "turn.completed"):
        return parsed

    # item events
    item = evt.get("item")
    if not isinstance(item, dict):
        return parsed

    item_type = item.get("type", "")

    def _cmd_as_text(value: object) -> str:
        if isinstance(value, str):
            return value
        if isinstance(value, list):
            return " ".join(str(v) for v in value)
        if value is None:
            return ""
        return str(value)

    # item.started with command_execution -> tool in progress
    if etype == "item.started" and item_type == "command_execution":
        cmd_str = _cmd_as_text(item.get("command"))
        parsed["type"] = "tool"
        parsed["tools"] = [{"name": "shell", "input": {"command": cmd_str}}]
        return parsed

    # item.completed
    if etype == "item.completed":
        # agent_message -> final result text
        if item_type == "agent_message":
            text = item.get("text", "")
            if isinstance(text, str) and text:
                parsed["type"] = "result"
                parsed["text"] = text
                # Short one-line agent updates are useful as live progress in Slack.
                if "\n" not in text and len(text) <= 180:
                    parsed["tools"] = [{"name": "assistant_status", "input": {"text": text}}]
            return parsed

        # command_execution completed -> tool with output
        if item_type == "command_execution":
            cmd_str = _cmd_as_text(item.get("command"))
            parsed["type"] = "tool"
            parsed["tools"] = [{"name": "shell", "input": {"command": cmd_str}}]
            output = item.get("aggregated_output", "")
            if isinstance(output, str) and output:
                parsed["text"] = output
            return parsed

        # reasoning -> text (model's thinking)
        if item_type == "reasoning":
            text = item.get("text", "")
            if isinstance(text, str) and text:
                parsed["type"] = "text"
                parsed["text"] = text
                parsed["tools"] = [{"name": "thinking", "input": {"text": text}}]
            return parsed

        # file_change -> tool
        if item_type == "file_change":
            parsed["type"] = "tool"
            parsed["tools"] = [{"name": "file_change", "input": item}]
            return parsed

        # mcp_tool_call -> tool
        if item_type == "mcp_tool_call":
            tool_name = item.get("name", "mcp_tool")
            parsed["type"] = "tool"
            parsed["tools"] = [{"name": tool_name, "input": item.get("arguments", {})}]
            return parsed

    # item.updated -> track progress but don't surface as result
    if etype == "item.updated":
        if item_type == "command_execution":
            output = item.get("aggregated_output", "")
            if isinstance(output, str) and output:
                parsed["type"] = "text"
                parsed["text"] = output
        return parsed

    return parsed


# ── Session usage ────────────────────────────────────────────────────────


def build_usage_cmd(
    session_id: str,
    working_dir: Optional[Path] = None,
) -> Optional[list[str]]:
    """Codex CLI does not support session usage queries."""
    return None


def parse_usage_output(stdout: str) -> Optional[Dict]:
    """Not supported for Codex backend."""
    return None
